{{- if and .Values.apiAuthentication.enabled .Values.apiAuthentication.ingress.enabled }}
{{- $hostname := .Values.apiAuthentication.ingress.hostname | default "" -}}
{{- if $hostname }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-authentication
  namespace: {{ .Values.global.namespace }}
  labels:
    app: api-authentication
    {{- with .Values.apiAuthentication.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.apiAuthentication.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl (toString $value) $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.apiAuthentication.ingress.ingressClassName }}
  ingressClassName: {{ tpl . $ }}
  {{- end }}
  rules:
    - host: {{ tpl $hostname $ | quote }}
      http:
        paths:
        - backend:
            service:
              name: api-authentication
              port:
                number: 80
          path: /storage
          pathType: Prefix
        - backend:
            service:
              name: api-authentication
              port:
                number: 5000
          path: /
          pathType: Prefix
  tls:
    - hosts:
      - {{ tpl $hostname $ }}
      secretName: tls-api-authentication-prod-cert
{{- end }}
{{- end }}