apiVersion: v2
name: kbot-self-hosted
version: 0.1.0
appVersion: "1.0"
description: A Helm chart for Kbot self-hosted installation including all microservices
type: application
home: https://www.konverso.ai/
keywords:
  - kbot
  - konverso
maintainers:
  - name: Konverso Team
dependencies:
  - name: clamav
    version: 3.7.1
    repository: https://wiremind.github.io/wiremind-helm-charts