{{- if .Values.apiAuthAntivirus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.apiAuthAntivirus.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: api-auth-antivirus
    {{- with .Values.apiAuthAntivirus.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: api-auth-antivirus
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: api-auth-antivirus
  revisionHistoryLimit: 2
  minReadySeconds: 15
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      {{- with .Values.apiAuthAntivirus.podExtraAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: api-auth-antivirus
        {{- with .Values.apiAuthAntivirus.podExtraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      {{- with .Values.apiAuthAntivirus.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiAuthAntivirus.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
          - name: APP_ENV
            value: "prod"
          - name: CLAMAV_SOCKET_HOST
            value: kbot-self-hosted-clamav.kbot.svc
          - name: CLAMAV_SOCKET_PORT
            value: "3310"
          - name: LOG_LEVEL
            value: {{ .Values.global.logLevel | default "warning" | quote }}
          - name: TENANT_SERVICE_URL
            value: {{ .Values.apiAuthAntivirus.tenantServiceUrl | quote }}
          image: {{ .Values.global.imageRegistry }}/api-auth-antivirus:{{ .Values.apiAuthAntivirus.image.tag }}
          name: api-auth-antivirus
          resources:
            {{- toYaml .Values.apiAuthAntivirus.resources | nindent 12 }}
          ports:
            - containerPort: 5000
              name: apirest
              protocol: TCP
            - containerPort: 8090
              name: actuator
              protocol: TCP
{{- end }}

