{{- if and .Values.apiAuthAntivirus.enabled .Values.apiAuthAntivirus.ingress.enabled }}
{{- $hostname := .Values.apiAuthAntivirus.ingress.hostname | default "" -}}
{{- if $hostname }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-auth-antivirus
  namespace: {{ .Values.global.namespace }}
  labels:
    app: api-auth-antivirus
    {{- with .Values.apiAuthAntivirus.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.apiAuthAntivirus.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl (toString $value) $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.apiAuthAntivirus.ingress.ingressClassName }}
  ingressClassName: {{ tpl . $ }}
  {{- end }}
  rules:
    - host: {{ tpl $hostname $ | quote }}
      http:
        paths:
        - backend:
            service:
              name: api-auth-antivirus
              port:
                name: apirest
          path: /
          pathType: Prefix
  tls:
    - hosts:
      - {{ tpl $hostname $ }}
      secretName: tls-api-auth-antivirus-prod-cert
{{- end }}
{{- end }}

