{{- if and .Values.apiAuthPdfConverter.enabled .Values.apiAuthPdfConverter.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scale-api-auth-pdf-converter
  namespace: {{ .Values.global.namespace }}
  annotations:
    autoscaling.keda.sh/paused: "false"
spec:
  scaleTargetRef:
    name: api-auth-pdf-converter
    kind: Deployment
  cooldownPeriod: {{ .Values.apiAuthPdfConverter.autoscaling.cooldownPeriod }}
  minReplicaCount: {{ .Values.apiAuthPdfConverter.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.apiAuthPdfConverter.autoscaling.maxReplicas }}
  pollingInterval: {{ .Values.apiAuthPdfConverter.autoscaling.pollingInterval }}
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: {{ .Values.apiAuthPdfConverter.autoscaling.cpuThreshold | quote }}
{{- end }}

