{{- if and .Values.apiAuthPdfConverter.enabled .Values.apiAuthPdfConverter.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: api-auth-pdf-converter
  name: {{ .Values.apiAuthPdfConverter.pvc.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.apiAuthPdfConverter.pvc.size }}
  {{- if .Values.apiAuthPdfConverter.pvc.storageClassName }}
  storageClassName: {{ .Values.apiAuthPdfConverter.pvc.storageClassName }}
  {{- end }}
  volumeMode: Filesystem
{{- end }}

