{{- if .Values.apiAuthPdfConverter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.apiAuthPdfConverter.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: api-auth-pdf-converter
    {{- with .Values.apiAuthPdfConverter.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: api-auth-pdf-converter
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: api-auth-pdf-converter
  revisionHistoryLimit: 2
  minReadySeconds: 15
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      {{- with .Values.apiAuthPdfConverter.podExtraAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: api-auth-pdf-converter
        {{- with .Values.apiAuthPdfConverter.podExtraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      containers:
        - name: api-auth-pdf-converter
          env:
          - name: APP_ENV
            value: "prod"
          - name: GOTENBERG_SERVICE_HOST
            value: "http://api-gotenberg.kbot.svc.cluster.local"
          - name: GOTENBERG_SERVICE_PORT
            value: "3000"
          - name: LOG_LEVEL
            value: {{ .Values.global.logLevel | default "warning" | quote }}
          - name: MODE
            value: "prod"
          - name: PDF_CONVERTER_STORAGE
            value: "storage-conversion"
          - name: PDF_CONVERTER_STORAGE_ROOT
            value: "/home/konverso"
          - name: TENANT_SERVICE_URL
            value: {{ .Values.apiAuthAntivirus.tenantServiceUrl | quote }}
          image: {{ .Values.global.imageRegistry }}/api-auth-pdf-converter:{{ .Values.apiAuthPdfConverter.image.tag }}
          resources:
            {{- toYaml .Values.apiAuthPdfConverter.resources | nindent 12 }}
          ports:
            - name: apirest
              containerPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /home/konverso/storage-conversion
              name: api-auth-pdf-converter-data
      volumes:
        - name: api-auth-pdf-converter-data
          persistentVolumeClaim:
            claimName: {{ .Values.apiAuthPdfConverter.pvc.name }}
{{- end }}

