{{- if and .Values.apiFiles.enabled .Values.apiFiles.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.apiFiles.configmap.name }}
  namespace: {{ .Values.global.namespace }}
data:
  nginx.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;
      server_tokens off;
      client_max_body_size 2G;
      client_body_timeout 120s;
      location /storage {
          root   /var/www;
          autoindex off;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
{{- end }}

