{{- if and .Values.apiFiles.enabled .Values.apiFiles.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: api-files
  name: {{ .Values.apiFiles.pvc.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.apiFiles.pvc.size }}
  {{- if .Values.apiFiles.pvc.storageClassName }}
  storageClassName: {{ .Values.apiFiles.pvc.storageClassName }}
  {{- end }}
  volumeMode: Filesystem
{{- end }}

