{{- if and .Values.apiFiles.enabled .Values.apiFiles.ingress.enabled }}
{{- $hostname := .Values.apiFiles.ingress.hostname | default "" -}}
{{- if $hostname }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: api-files
    {{- with .Values.apiFiles.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.apiFiles.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl (toString $value) $ | quote }}
    {{- end }}
  {{- end }}
  name: api-files
  namespace: {{ .Values.global.namespace }}
spec:
  {{- with .Values.apiFiles.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: {{ $hostname | quote }}
      http:
        paths:
        - backend:
            service:
              name: api-files
              port:
                number: 80
          path: /storage
          pathType: Prefix
        - backend:
            service:
              name: api-files
              port:
                number: 5000
          path: /
          pathType: Prefix
  tls:
    - hosts:
      - {{ $hostname }}
      secretName: tls-api-files-prod-cert
{{- end }}
{{- end }}

