{{- if .Values.apiFiles.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api-files
  namespace: {{ .Values.global.namespace }}
  labels:
    app: api-files
  {{- with .Values.apiFiles.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  ports:
    - name: storage
      port: 80
      protocol: TCP
      targetPort: 80
    - name: apirest
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: api-files
{{- end }}

