{{- if and .Values.apiOauth2Proxy.enabled .Values.apiOauth2Proxy.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scale-api-oauth2-proxy
  namespace: {{ .Values.global.namespace }}
  annotations:
    autoscaling.keda.sh/paused: "false"
spec:
  scaleTargetRef:
    name: api-oauth2-proxy
    kind: Deployment
  cooldownPeriod: {{ .Values.apiOauth2Proxy.autoscaling.cooldownPeriod }}
  minReplicaCount: {{ .Values.apiOauth2Proxy.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.apiOauth2Proxy.autoscaling.maxReplicas }}
  pollingInterval: {{ .Values.apiOauth2Proxy.autoscaling.pollingInterval }}
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: {{ .Values.apiOauth2Proxy.autoscaling.cpuThreshold | quote }}
      containerName: "api-oauth2-proxy"
{{- end }}

