{{- if .Values.apiOauth2Proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.apiOauth2Proxy.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: api-oauth2-proxy
    {{- with .Values.apiOauth2Proxy.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: api-oauth2-proxy
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: api-oauth2-proxy
  revisionHistoryLimit: 2
  minReadySeconds: 15
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      {{- with .Values.apiOauth2Proxy.podExtraAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: api-oauth2-proxy
        {{- with .Values.apiOauth2Proxy.podExtraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      {{- with .Values.apiOauth2Proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiOauth2Proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
          - name: APP_ENV
            value: "prod"
          - name: API_KEYS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.secretName | default "kbot-secrets" }}
                key: oauth2-proxy-api-key
          - name: LOG_LEVEL
            value: {{ .Values.global.logLevel | default "warning" | quote }}
          - name: TENANT_SERVICE_URL
            value: {{ .Values.apiOauth2Proxy.tenantServiceUrl | quote }}
          image: {{ .Values.global.imageRegistry }}/api-oauth2-proxy:{{ .Values.apiOauth2Proxy.image.tag }}
          name: api-oauth2-proxy
          resources:
            {{- toYaml .Values.apiOauth2Proxy.resources | nindent 12 }}
          ports:
            - containerPort: 5000
              name: apirest
              protocol: TCP
            - containerPort: 8090
              name: actuator
              protocol: TCP
{{- end }}

